name: Plugin CI
on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md, gradle.properties, .github/.release-please-manifest.json ]

  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore: [ README.md, gradle.properties, .github/.release-please-manifest.json ]

jobs:
  validate-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

  build-and-test:
    needs: [ validate-wrapper ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
